
******************************
XACCESS$ROOT:[INSTALL]INSTALL.COM;11

$ MEMTEXT :== @XACCESS$ROOT:[INSTALL]CONVERT -
                           XACCESS$ROOT:[INSTALL]MEMTEXT.EXE """MEM/TEXT"""
$ MEMTEXT 'FILENAME'.MEM 'FILENAME'.DOC
